/**
 * Generate COPY.md (all public draft copy) and the screenshot checklist in
 * ASSETS.md from the catalog, so Marawan can review without reading code.
 * Run: node --experimental-strip-types scripts/docs.mjs
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const { products, solutions, lifecycle, pillars } = await import("../src/lib/catalog.ts");
const { copy } = await import("../src/lib/copy.ts");

const root = process.cwd();
const shotsDir = join(root, "public", "shots");
const hasShot = (key) => ["webp", "png", "jpg"].some((e) => existsSync(join(shotsDir, `${key}.${e}`)));

// ── COPY.md ──────────────────────────────────────────────────────────
let md = `# Draft copy — not approved

Marawan signs off before production. Source of truth in code: \`src/lib/copy.ts\`
(homepage and shared pages) and \`src/lib/catalog.ts\` (every product page).
Generated by \`node --experimental-strip-types scripts/docs.mjs\`. Do not edit by hand.

## Homepage

**Headline:** ${copy.hero.headline}

**Sub:** ${copy.hero.sub}

**Buttons:** ${copy.cta.primary} · ${copy.cta.secondary}

### Lifecycle
${lifecycle.map((s, i) => `${i + 1}. **${s.name}.** ${s.body}`).join("\n")}

`;
for (const key of ["sell", "discovery", "delivery", "catering", "guest", "growth", "operations", "analytics", "scale", "integrations"]) {
  const s = copy[key];
  md += `### ${s.heading}\n${s.sub ? `\n${s.sub}\n` : ""}\n`;
}
md += `### ${copy.pricing.heading}\n\n**${copy.pricing.stat}** · ${copy.pricing.line}\n\n${copy.pricing.body}\n\n${copy.pricing.more}\n\n`;
md += `### ${copy.customerProof.heading}\n\n${copy.customerProof.body}\n\n_${copy.customerProof.footnote}_\n\n`;
md += `### ${copy.faq.heading}\n\n${copy.faq.items.map((q) => `- **${q.question}** ${q.answer}`).join("\n")}\n\n`;
md += `### Final call to action\n\n**${copy.finalCta.heading}** ${copy.finalCta.body}\n\n`;

md += `## Menu check (/menu-check)\n\n**${copy.menuCheck.headline}** ${copy.menuCheck.sub}\n\n> Placeholder dish names on the right ticket: ${copy.menuCheck.right.dishes.join(", ")}. Replace with real names from the Orlando menu.\n\n`;

for (const pillar of ["sell", "grow", "operate", "scale"]) {
  md += `## ${pillars[pillar].name}\n\n`;
  for (const p of products.filter((x) => x.pillar === pillar)) {
    md += `### ${p.name} (/${p.slug})${p.inMenu ? "" : " — not in mega-menu"}\n\n**${p.headline}** ${p.sub}\n\n${p.capabilitiesTitle ?? "What you can do"}:\n${p.capabilities.map((c) => `- ${c}`).join("\n")}\n`;
    if (p.comingSoon?.length) md += `\nComing soon: ${p.comingSoon.join(", ")}\n`;
    if (p.flow) md += `\n${p.flow.title}: ${p.flow.steps.join(" → ")}\n`;
    if (p.notes?.length) md += `\n${p.notes.map((n) => `_${n}_`).join("\n\n")}\n`;
    md += "\n";
  }
}
md += `## Solutions\n\n`;
for (const s of solutions) {
  md += `### ${s.name} (/solutions/${s.slug})\n\n**${s.headline}** ${s.sub}\n\n${s.points.map((x) => `- ${x}`).join("\n")}\n\n`;
}
md += `## Company\n\n**About:** ${copy.about.headline}\n\n${copy.about.body.join("\n\n")}\n\n**Contact:** ${copy.contact.headline} ${copy.contact.body}\n\n**Articles:** ${copy.blog.body}\n\n**Legal:** /privacy and /terms are hosting shells. Text is supplied by Marawan and pasted verbatim into src/lib/legal.ts; nothing legal is written here.\n`;
writeFileSync(join(root, "COPY.md"), md);

// ── ASSETS.md screenshot checklist ───────────────────────────────────
const shots = new Map();
const add = (shot, where) => {
  const cur = shots.get(shot.key) ?? { ...shot, where: [] };
  cur.where.push(where);
  shots.set(shot.key, cur);
};
for (const s of copy.hero.screens) add(s, "Homepage hero");
add(copy.customerProof.shot, "Homepage customer proof");
for (const p of products) for (const s of p.shots) add(s, `/${p.slug}`);

const rows = [...shots.values()]
  .sort((a, b) => (a.priority === b.priority ? 0 : a.priority === "must" ? -1 : 1))
  .map((s) => `| \`${s.key}\` | ${s.priority === "must" ? "Must have" : "Helpful"} | ${s.kind === "phone" ? "phone 390×844" : "desktop 1280×800"} | ${s.label} | ${s.where.join(", ")} | ${hasShot(s.key) ? "yes" : "missing"} |`)
  .join("\n");

const assetsPath = join(root, "ASSETS.md");
let assets = readFileSync(assetsPath, "utf8");
const start = "<!-- shots:start -->";
const end = "<!-- shots:end -->";
const table = `${start}\nDrop each file at \`public/shots/<key>.webp\` (PNG or JPG also work), or run \`npm run capture\` with a filled-in \`shots.config.json\`. Must-have slots show a captioned empty frame until the file exists; helpful slots stay hidden until then. Keys are shared across pages on purpose. Generated by \`scripts/docs.mjs\`.\n\n| Key | Priority | Size | What it shows | Used on | Present |\n|-----|----------|------|---------------|---------|---------|\n${rows}\n${end}`;
assets = assets.includes(start)
  ? assets.replace(new RegExp(`${start}[\\s\\S]*${end}`), table)
  : `${assets.trimEnd()}\n\n## Screenshot checklist\n\n${table}\n`;
writeFileSync(assetsPath, assets);
console.log(`COPY.md written; ${shots.size} screenshot slots listed in ASSETS.md (${[...shots.values()].filter((s) => hasShot(s.key)).length} present)`);
