#!/usr/bin/env node
/**
 * Generates docs/marketing-site/SHOTS.md from the same placement list and
 * catalog the screenshot frames read (src/lib/shot-placements.ts,
 * src/lib/catalog.ts, src/lib/shot-files.ts), so the shot list can't drift.
 *
 *   node scripts/shots-doc.mjs           write the file (local builds, `npm run shots`)
 *   node scripts/shots-doc.mjs --check   fail if the committed file is out of date
 *
 * Runs before every build (`prebuild`). On CI (Vercel sets CI and VERCEL)
 * it checks instead of writing, so a stale committed file fails the build.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createJiti } from "jiti";

const jiti = createJiti(import.meta.url);
const { shotRows } = await jiti.import("../src/lib/shot-placements.ts");
const { findShot, shotSize } = await jiti.import("../src/lib/shot-files.ts");

const OUT = join(process.cwd(), "docs", "marketing-site", "SHOTS.md");
const KIND = { desktop: "Desktop", phone: "Phone", tablet: "Tablet", photo: "Photo" };

const cell = (text) => String(text).replace(/\|/g, "\\|");

function row(shot, labels, where) {
  const size = shotSize(shot);
  const found = findShot(shot.key);
  return `| \`${shot.key}.webp\` | ${KIND[shot.kind ?? "desktop"]} ${size.width}×${size.height} | ${cell(labels.join("; "))} | ${cell(where)} | ${found ? `Done (\`${found.replace("/shots/", "")}\`)` : "Missing"} |`;
}

const HEADER = ["| File | Size | What it should show | Where it appears | Status |", "|---|---|---|---|---|"];

export function render() {
  const rows = shotRows();
  const placed = rows.filter((r) => r.placements.length);
  const unplaced = rows.filter((r) => !r.placements.length);
  const done = placed.filter((r) => findShot(r.shot.key)).length;
  const lines = [
    "# Product screenshots",
    "",
    "Generated by `scripts/shots-doc.mjs` from `src/lib/shot-placements.ts` and `src/lib/catalog.ts`, the same list the screenshot frames read. Don't edit it by hand: run `npm run shots`. The build regenerates it, and a Vercel build fails if the committed copy is out of date.",
    "",
    `**${done} of ${placed.length} done.**`,
    "",
    "Drop each file into `public/shots/` with the name shown, at the size shown (WebP preferred; PNG or JPG also work). wuntab.com shows nothing where a shot is missing. Preview deployments show a placeholder box with the file name and size in its place.",
    "",
    ...HEADER,
    ...placed.map((r) => row(r.shot, r.labels, r.placements.map((p) => `\`${p.page}\` ${p.section}`).join("<br>"))),
  ];
  if (unplaced.length) {
    lines.push(
      "",
      "## In the catalog, not on any page yet",
      "",
      "These belong to products without a page. They aren't in the count above.",
      "",
      ...HEADER,
      ...unplaced.map((r) => row(r.shot, r.labels, "Not on any page yet")),
    );
  }
  return `${lines.join("\n")}\n`;
}

const check = process.argv.includes("--check") || Boolean(process.env.CI || process.env.VERCEL);
const next = render();
let current = "";
try {
  current = readFileSync(OUT, "utf8");
} catch {
  current = "";
}

if (check) {
  if (current !== next) {
    console.error(
      "docs/marketing-site/SHOTS.md is out of date. Run `npm run shots` and commit the result.",
    );
    process.exit(1);
  }
  console.log("shots-doc: SHOTS.md is up to date");
} else {
  if (current !== next) writeFileSync(OUT, next);
  console.log(`shots-doc: ${current === next ? "unchanged" : "wrote"} docs/marketing-site/SHOTS.md`);
}
